### ISSUE TITLE
CodonOptimize must have an EnforceTranslation constraint

### ISSUE THREAD

**Issue by Zulko** [olgatsiouri1996/biomisc#1]
Hello! If you simply use `CodonOptimize`, without `EnforceTranslation`, then the codon optimization can actually change the protein sequence, which is very dangerous! Sorry if the documentation is unclear on this subject!

This [line](https://github.com/olgatsiouri1996/biomisc/blob/c2e35911afb5203afd8a89aa57413679a588d2fd/synbio/codon_optimize_cds.py#L15) should be:
```python
    constraints=[EnforceTranslation()]
    objectives=[CodonOptimize(species= args['organism'])])
```

**Comment by olgatsiouri1996** [comment]
Thank you very much i fixed it!
